import type { Metadata } from 'next'
import Link from 'next/link'
import PageHero from '@/components/ui/PageHero'
import { books, music } from '@/data/creative-works'

export const metadata: Metadata = {
  title: 'Books & Music',
  description: 'Books, songs, and creative works from Faith Connect Community.',
}

function Cover({ title, image, label }: { title: string; image?: string; label: string }) {
  return image ? <img src={image} alt={`${title} cover`} className="aspect-[4/5] w-full object-cover" /> : <div className="flex aspect-[4/5] flex-col justify-between bg-navy-950 p-6 text-white"><span className="text-xs font-extrabold uppercase tracking-[.2em] text-gold-400">Faith Connect</span><p className="font-display text-2xl font-bold leading-tight">{title}</p><span className="text-xs font-bold uppercase tracking-[.18em] text-white/60">{label}</span></div>
}

export default function BooksMusicPage() {
  return <main id="main-content">
    <PageHero eyebrow="Books & music" title="Words and songs that carry hope.">Explore books and musical works created to strengthen faith, encourage purpose, and serve the wider community.</PageHero>
    <section className="bg-white py-20"><div className="page-shell"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Written works</p><h2 className="mt-4 font-display text-4xl font-bold text-navy-950">Books</h2></div><p className="max-w-xl leading-7 text-slate-600">Thoughtful writing that inspires growth, purpose, and a deeper walk with God.</p></div>{books.length ? <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{books.map((book) => <article key={book.title} className="overflow-hidden rounded-3xl border border-slate-200 bg-cream-50"><Cover title={book.title} image={book.coverImage} label="Book" /><div className="p-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-gold-500">{book.format}</p><h3 className="mt-3 font-display text-2xl font-bold text-navy-950">{book.title}</h3><p className="mt-3 leading-7 text-slate-600">{book.description}</p>{book.purchaseUrl && <a href={book.purchaseUrl} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex font-extrabold text-navy-950 underline decoration-gold-400 decoration-2 underline-offset-6">Get this book ↗</a>}</div></article>)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-gold-500/50 bg-cream-50 p-8 text-center sm:p-12"><p className="font-display text-2xl font-bold text-navy-950">Books are being prepared for this collection.</p><p className="mx-auto mt-3 max-w-xl leading-7 text-slate-600">New releases and ways to access them will be shared here soon.</p></div>}</div></section>
    <section className="bg-cream-50 py-20"><div className="page-shell"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">Sound & worship</p><h2 className="mt-4 font-display text-4xl font-bold text-navy-950">Music</h2></div><p className="max-w-xl leading-7 text-slate-600">Songs and productions created to bring encouragement, worship, and positive change into everyday life.</p></div>{music.length ? <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{music.map((release) => <article key={release.title} className="overflow-hidden rounded-3xl bg-white ring-1 ring-slate-200"><Cover title={release.title} image={release.coverImage} label={release.type} /><div className="p-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-gold-500">{release.type}</p><h3 className="mt-3 font-display text-2xl font-bold text-navy-950">{release.title}</h3>{release.artist && <p className="mt-2 text-sm font-semibold text-slate-500">{release.artist}</p>}{release.listenUrl && <a href={release.listenUrl} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex font-extrabold text-navy-950 underline decoration-gold-400 decoration-2 underline-offset-6">Listen now ↗</a>}</div></article>)}</div> : <div className="mt-10 rounded-3xl border border-dashed border-gold-500/50 bg-white p-8 text-center sm:p-12"><p className="font-display text-2xl font-bold text-navy-950">Music releases are coming soon.</p><p className="mx-auto mt-3 max-w-xl leading-7 text-slate-600">Songs and productions will be available here with direct listening links.</p></div>}</div></section>
    <section className="bg-navy-950 py-16 text-white"><div className="page-shell flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow text-gold-400">Stay connected</p><h2 className="mt-3 font-display text-3xl font-bold">Be first to hear about new releases.</h2></div><Link href="/contact" className="w-fit rounded-full bg-gold-400 px-6 py-3 font-extrabold text-navy-950 no-underline">Contact Faith Connect</Link></div></section>
  </main>
}
