import type { Metadata } from 'next'
import DonationPanel from '@/components/donate/DonationPanel'

export const metadata: Metadata = { title: 'Donate', description: 'Give securely to support the ministry and community work of Faith Connect Community NPC.' }

export default function DonatePage() {
  const bankName = process.env.NEXT_PUBLIC_EFT_BANK_NAME
  const accountName = process.env.NEXT_PUBLIC_EFT_ACCOUNT_NAME
  const accountNumber = process.env.NEXT_PUBLIC_EFT_ACCOUNT_NUMBER
  const branchCode = process.env.NEXT_PUBLIC_EFT_BRANCH_CODE
  const eftReady = bankName && accountName && accountNumber && branchCode
  return (
    <main id="main-content">
      <section className="soft-grid bg-navy-950 py-20 text-white sm:py-28"><div className="page-shell grid gap-12 lg:grid-cols-[1fr_.85fr] lg:items-center"><div><p className="eyebrow text-gold-400">Partner with the mission</p><h1 className="mt-5 font-display text-5xl font-bold leading-tight sm:text-6xl">Give with purpose.<br />Create lasting impact.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">Every gift helps us connect people to Christ and serve communities through ministry, education, mentoring, and practical support.</p><p className="mt-8 border-l-2 border-gold-400 pl-5 font-display text-xl italic text-white/85">“Each of you should give what you have decided in your heart to give.” <span className="mt-1 block font-sans text-xs font-bold not-italic uppercase tracking-widest text-gold-400">2 Corinthians 9:7</span></p></div><DonationPanel /></div></section>
      <section className="bg-white py-20"><div className="page-shell grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Where your gift goes</p><h2 className="mt-4 font-display text-4xl font-bold text-navy-950">Stewarded with care.</h2><p className="mt-5 leading-7 text-slate-600">Donations support Faith Connect Community NPC’s charitable objects and programmes. Our board provides financial oversight with a commitment to integrity, accountability, and responsible stewardship.</p><ul className="mt-7 grid gap-3 text-sm font-bold text-navy-900"><li>✓ Worship, discipleship, and pastoral care</li><li>✓ Community outreach and practical relief</li><li>✓ Youth, family, and leadership development</li><li>✓ Education and sustainable skills initiatives</li></ul></div><div className="rounded-3xl bg-cream-50 p-7 ring-1 ring-slate-200 sm:p-9"><h2 className="font-display text-2xl font-bold text-navy-950">Give by EFT</h2>{eftReady ? <dl className="mt-6 grid grid-cols-[auto_1fr] gap-x-5 gap-y-3 text-sm"><dt className="text-slate-500">Account</dt><dd className="font-bold text-navy-950">{accountName}</dd><dt className="text-slate-500">Bank</dt><dd className="font-bold text-navy-950">{bankName}</dd><dt className="text-slate-500">Account number</dt><dd className="font-bold text-navy-950">{accountNumber}</dd><dt className="text-slate-500">Branch code</dt><dd className="font-bold text-navy-950">{branchCode}</dd><dt className="text-slate-500">Reference</dt><dd className="font-bold text-navy-950">Your name + purpose</dd></dl> : <p className="mt-4 leading-7 text-slate-600">Banking details are available directly from the church while secure publication is being finalised. Email <a className="font-bold text-navy-900 underline" href="mailto:info@faithconnect.community?subject=EFT%20giving%20details">info@faithconnect.community</a>.</p>}<p className="mt-6 text-xs leading-5 text-slate-500">For donation confirmations or questions about the use of funds, please contact our team. Tax deductibility depends on the organisation’s current SARS approval and the purpose of the gift; no Section 18A receipt is promised on this site.</p></div></div></section>
    </main>
  )
}
